### ISSUE TITLE
User Story 1 - Eingabe und Entity User Story

### ISSUE THREAD

**Issue by MartinX3** [MartinX3/Mid-Term-Project_HBRS-SA_S3_SE1#1]
Beachte die technischen Anforderungen im Wiki!

Eingabedialog für Entwickler für die notwendigen Daten einer User Story

Notwendige Daten der US Entity:
- Beschreibung: String
- Details: String
- Akzeptanzkriterien: String
- Epic: String
- Mehrwert: int (Wertbereich: 1-5)
- Strafe: int (Wertbereich: 1-5)
- Risiko: int (Wertbereich: 1-5)
- Aufwand: int
- Prio: double (als Getter)

Errechnung der Priorität (Auslagern in statische Methode der Klasse Utils):
Prio = (Mehrwert + Strafe)/(Aufwand + Risiko)

_Sent from my Nexus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MartinX3** [comment]
Eingabedialog fehlt!

**Comment by MartinX3** [comment]
Der Text soll sich ab der 2. US nicht wiederholen
`[]Willkommen in der USER-Story Eingabe[]\nUm eine User-Story einzugeben, folgen sie den Anweisungen.\n`

Rechtschreibfehler in beschreibung, epic, aufwand

Auflisten der US
Ab der 2. US muss das ', ' weg.
Bsp.:
```
-----------------------------------------------------------------------------------------------------------------
, Beschreibung: Bl
```

Auflisten der US
Die Umrahmung mit [] muss weg.

Wenn es darum geht, Zahlen einzugeben, erhalte ich den Fehler java.util.InputMismatchException
Anschließend werde ich gefragt, ob ich noch eine US eingeben will
1. Fehler durch hinweis ersetzen
2. Erneute Eingabe des Wertes ermöglichen

Bei der Eingabe kann ich Werte außerhalb des Zahlenbereichs eingeben
Korrekt wäre:
1. Hinweis einbauen
2. Erneute Eingabe des Wertes ermöglichen

Warum wird bei "Aufwand" ein Wert von 1-5 erwartet?

**Comment by MartinX3** [comment]
Welchen Mehrwert erwarten Sie? (1-5)
aa
Möchten sie noch eine User-Story eingeben?(y/n)
java.util.InputMismatchException
	at java.util.Scanner.throwFor(Scanner.java:864)
	at java.util.Scanner.next(Scanner.java:1485)
	at java.util.Scanner.nextInt(Scanner.java:2117)
	at java.util.Scanner.nextInt(Scanner.java:2076)
	at org.bonn.se.ws17.midterm.EingabeUtil.checker(EingabeUtil.java:37)
	at org.bonn.se.ws17.midterm.EingabeUtil.eingabe(EingabeUtil.java:26)
	at org.bonn.se.ws17.midterm.Main.main(Main.java:15)

**Comment by MartinX3** [comment]
Ein negativer Aufwand darf nicht möglich sein!

**Comment by MartinX3** [comment]
Es wird eine Zahl größer Null gefordert, soweit richtig, aber Null ist nicht negativ.

```
Der Aufwand kann nicht negativ sein. Bitte geben sie eine positive Zahl ein.
0
```
